python:
  - "2.7"
  - "2.6"
  - "3.2"
before_install:
  - pip install --user -r ./build/build-requirements.txt
script:
  - make test
  - make setup
  - make package
after_success:
  - >
    if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
      if docker login --help  | grep -q '\-e'; then
        docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      else
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
      fi
      echo "Pushing built Docker Image to: $TRAVIS_REPO_SLUG" ;
      docker push $TRAVIS_REPO_SLUG ;
    fi
  - "[ -e \"~/.docker/config.json\" ] && shred -n 30 -u -z ~/.docker/config.json"
